### ISSUE TITLE
Error building docs

### ISSUE THREAD

**Issue by tfogo** [carbon-io/carbon-io#22]
I was building the docs and ran into an error:

```
Exception occurred:
  File "conf.py", line 418, in patch_object_description
    app.domains['js'].roles['class'] = JSXRefRole()
AttributeError: 'Sphinx' object has no attribute 'domains'
```

When I comment out line 418 in `docs/common/conf.py` it seems to build okay. 

The comment above that line says "Patch Javascript domain to remove parens on class refs". What does that mean exactly?

**Comment by gregbanks** [comment]
updated docs/common to get new requirements.txt with sphinx requirement bounded at <1.6
