### ISSUE TITLE
RTD version menu

### ISSUE THREAD

**Issue by chrisckchang** [carbon-io/carbon-io#8]
![image](https://cloud.githubusercontent.com/assets/3644260/20572630/116547c4-b161-11e6-88fe-c147479e76eb.png)

Edits:

I'd like for the closed/hover states to look like how it does now on docs.carbon.io. Instead of the ReadTheDocs logo, I'd like for it to say Carbon.io and "version: latest" to be aligned right.

On the Expanded view, I'd like for the bottom "Documentation hosted by RTD" to be removed (even though we love you guys!). I'd also like the bottom border for the "version:latest" on expanded view similar to how it is right now on docs.carbon.io.

**Comment by willshulman** [comment]
What do we have to do to get RTD honoring version numbers?
